<?php
namespace EDAM\Limits;

/**
 * Autogenerated by Thrift Compiler (0.9.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Exception\TApplicationException;

class Constants
{
    public static $EDAM_ATTRIBUTE_LEN_MIN = 1;

    public static $EDAM_ATTRIBUTE_LEN_MAX = 4096;

    public static $EDAM_ATTRIBUTE_REGEX = "^[^\\p{Cc}\\p{Zl}\\p{Zp}]{1,4096}\$";

    public static $EDAM_ATTRIBUTE_LIST_MAX = 100;

    public static $EDAM_ATTRIBUTE_MAP_MAX = 100;

    public static $EDAM_GUID_LEN_MIN = 36;

    public static $EDAM_GUID_LEN_MAX = 36;

    public static $EDAM_GUID_REGEX = "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\$";

    public static $EDAM_EMAIL_LEN_MIN = 6;

    public static $EDAM_EMAIL_LEN_MAX = 255;

    public static $EDAM_EMAIL_LOCAL_REGEX = "^[A-Za-z0-9!#\$%&'*+/=?^_`{|}~-]+(\\.[A-Za-z0-9!#\$%&'*+/=?^_`{|}~-]+)*\$";

    public static $EDAM_EMAIL_DOMAIN_REGEX = "^[A-Za-z0-9-]+(\\.[A-Za-z0-9-]+)*\\.([A-Za-z]{2,})\$";

    public static $EDAM_EMAIL_REGEX = "^[A-Za-z0-9!#\$%&'*+/=?^_`{|}~-]+(\\.[A-Za-z0-9!#\$%&'*+/=?^_`{|}~-]+)*@[A-Za-z0-9-]+(\\.[A-Za-z0-9-]+)*\\.([A-Za-z]{2,})\$";

    public static $EDAM_VAT_REGEX = "[A-Za-z]{2}.+";

    public static $EDAM_TIMEZONE_LEN_MIN = 1;

    public static $EDAM_TIMEZONE_LEN_MAX = 32;

    public static $EDAM_TIMEZONE_REGEX = "^([A-Za-z_-]+(/[A-Za-z_-]+)*)|(GMT(-|\\+)[0-9]{1,2}(:[0-9]{2})?)\$";

    public static $EDAM_MIME_LEN_MIN = 3;

    public static $EDAM_MIME_LEN_MAX = 255;

    public static $EDAM_MIME_REGEX = "^[A-Za-z]+/[A-Za-z0-9._+-]+\$";

    public static $EDAM_MIME_TYPE_GIF = "image/gif";

    public static $EDAM_MIME_TYPE_JPEG = "image/jpeg";

    public static $EDAM_MIME_TYPE_PNG = "image/png";

    public static $EDAM_MIME_TYPE_WAV = "audio/wav";

    public static $EDAM_MIME_TYPE_MP3 = "audio/mpeg";

    public static $EDAM_MIME_TYPE_AMR = "audio/amr";

    public static $EDAM_MIME_TYPE_AAC = "audio/aac";

    public static $EDAM_MIME_TYPE_M4A = "audio/mp4";

    public static $EDAM_MIME_TYPE_MP4_VIDEO = "video/mp4";

    public static $EDAM_MIME_TYPE_INK = "application/vnd.evernote.ink";

    public static $EDAM_MIME_TYPE_PDF = "application/pdf";

    public static $EDAM_MIME_TYPE_DEFAULT = "application/octet-stream";

    public static $EDAM_MIME_TYPES = array(
      "image/gif" => true,
      "image/jpeg" => true,
      "image/png" => true,
      "audio/wav" => true,
      "audio/mpeg" => true,
      "audio/amr" => true,
      "application/vnd.evernote.ink" => true,
      "application/pdf" => true,
      "video/mp4" => true,
      "audio/aac" => true,
      "audio/mp4" => true,
    );

    public static $EDAM_SEARCH_QUERY_LEN_MIN = 0;

    public static $EDAM_SEARCH_QUERY_LEN_MAX = 1024;

    public static $EDAM_SEARCH_QUERY_REGEX = "^[^\\p{Cc}\\p{Zl}\\p{Zp}]{0,1024}\$";

    public static $EDAM_HASH_LEN = 16;

    public static $EDAM_USER_USERNAME_LEN_MIN = 1;

    public static $EDAM_USER_USERNAME_LEN_MAX = 64;

    public static $EDAM_USER_USERNAME_REGEX = "^[a-z0-9]([a-z0-9_-]{0,62}[a-z0-9])?\$";

    public static $EDAM_USER_NAME_LEN_MIN = 1;

    public static $EDAM_USER_NAME_LEN_MAX = 255;

    public static $EDAM_USER_NAME_REGEX = "^[^\\p{Cc}\\p{Zl}\\p{Zp}]{1,255}\$";

    public static $EDAM_TAG_NAME_LEN_MIN = 1;

    public static $EDAM_TAG_NAME_LEN_MAX = 100;

    public static $EDAM_TAG_NAME_REGEX = "^[^,\\p{Cc}\\p{Z}]([^,\\p{Cc}\\p{Zl}\\p{Zp}]{0,98}[^,\\p{Cc}\\p{Z}])?\$";

    public static $EDAM_NOTE_TITLE_LEN_MIN = 1;

    public static $EDAM_NOTE_TITLE_LEN_MAX = 255;

    public static $EDAM_NOTE_TITLE_REGEX = "^[^\\p{Cc}\\p{Z}]([^\\p{Cc}\\p{Zl}\\p{Zp}]{0,253}[^\\p{Cc}\\p{Z}])?\$";

    public static $EDAM_NOTE_CONTENT_LEN_MIN = 0;

    public static $EDAM_NOTE_CONTENT_LEN_MAX = 5242880;

    public static $EDAM_APPLICATIONDATA_NAME_LEN_MIN = 3;

    public static $EDAM_APPLICATIONDATA_NAME_LEN_MAX = 32;

    public static $EDAM_APPLICATIONDATA_VALUE_LEN_MIN = 0;

    public static $EDAM_APPLICATIONDATA_VALUE_LEN_MAX = 4092;

    public static $EDAM_APPLICATIONDATA_ENTRY_LEN_MAX = 4095;

    public static $EDAM_APPLICATIONDATA_NAME_REGEX = "^[A-Za-z0-9_.-]{3,32}\$";

    public static $EDAM_APPLICATIONDATA_VALUE_REGEX = "^[^\\p{Cc}]{0,4092}\$";

    public static $EDAM_NOTEBOOK_NAME_LEN_MIN = 1;

    public static $EDAM_NOTEBOOK_NAME_LEN_MAX = 100;

    public static $EDAM_NOTEBOOK_NAME_REGEX = "^[^\\p{Cc}\\p{Z}]([^\\p{Cc}\\p{Zl}\\p{Zp}]{0,98}[^\\p{Cc}\\p{Z}])?\$";

    public static $EDAM_NOTEBOOK_STACK_LEN_MIN = 1;

    public static $EDAM_NOTEBOOK_STACK_LEN_MAX = 100;

    public static $EDAM_NOTEBOOK_STACK_REGEX = "^[^\\p{Cc}\\p{Z}]([^\\p{Cc}\\p{Zl}\\p{Zp}]{0,98}[^\\p{Cc}\\p{Z}])?\$";

    public static $EDAM_PUBLISHING_URI_LEN_MIN = 1;

    public static $EDAM_PUBLISHING_URI_LEN_MAX = 255;

    public static $EDAM_PUBLISHING_URI_REGEX = "^[a-zA-Z0-9.~_+-]{1,255}\$";

    public static $EDAM_PUBLISHING_URI_PROHIBITED = array(
      ".." => true,
    );

    public static $EDAM_PUBLISHING_DESCRIPTION_LEN_MIN = 1;

    public static $EDAM_PUBLISHING_DESCRIPTION_LEN_MAX = 200;

    public static $EDAM_PUBLISHING_DESCRIPTION_REGEX = "^[^\\p{Cc}\\p{Z}]([^\\p{Cc}\\p{Zl}\\p{Zp}]{0,198}[^\\p{Cc}\\p{Z}])?\$";

    public static $EDAM_SAVED_SEARCH_NAME_LEN_MIN = 1;

    public static $EDAM_SAVED_SEARCH_NAME_LEN_MAX = 100;

    public static $EDAM_SAVED_SEARCH_NAME_REGEX = "^[^\\p{Cc}\\p{Z}]([^\\p{Cc}\\p{Zl}\\p{Zp}]{0,98}[^\\p{Cc}\\p{Z}])?\$";

    public static $EDAM_USER_PASSWORD_LEN_MIN = 6;

    public static $EDAM_USER_PASSWORD_LEN_MAX = 64;

    public static $EDAM_USER_PASSWORD_REGEX = "^[A-Za-z0-9!#\$%&'()*+,./:;<=>?@^_`{|}~\\[\\]\\\\-]{6,64}\$";

    public static $EDAM_BUSINESS_URI_LEN_MAX = 32;

    public static $EDAM_NOTE_TAGS_MAX = 100;

    public static $EDAM_NOTE_RESOURCES_MAX = 1000;

    public static $EDAM_USER_TAGS_MAX = 100000;

    public static $EDAM_BUSINESS_TAGS_MAX = 100000;

    public static $EDAM_USER_SAVED_SEARCHES_MAX = 100;

    public static $EDAM_USER_NOTES_MAX = 100000;

    public static $EDAM_BUSINESS_NOTES_MAX = 500000;

    public static $EDAM_USER_NOTEBOOKS_MAX = 250;

    public static $EDAM_BUSINESS_NOTEBOOKS_MAX = 5000;

    public static $EDAM_USER_RECENT_MAILED_ADDRESSES_MAX = 10;

    public static $EDAM_USER_MAIL_LIMIT_DAILY_FREE = 50;

    public static $EDAM_USER_MAIL_LIMIT_DAILY_PREMIUM = 200;

    public static $EDAM_USER_UPLOAD_LIMIT_FREE = 62914560;

    public static $EDAM_USER_UPLOAD_LIMIT_PREMIUM = 1073741824;

    public static $EDAM_USER_UPLOAD_LIMIT_BUSINESS = 1073741824;

    public static $EDAM_NOTE_SIZE_MAX_FREE = 26214400;

    public static $EDAM_NOTE_SIZE_MAX_PREMIUM = 104857600;

    public static $EDAM_RESOURCE_SIZE_MAX_FREE = 26214400;

    public static $EDAM_RESOURCE_SIZE_MAX_PREMIUM = 104857600;

    public static $EDAM_USER_LINKED_NOTEBOOK_MAX = 100;

    public static $EDAM_NOTEBOOK_SHARED_NOTEBOOK_MAX = 250;

    public static $EDAM_NOTE_CONTENT_CLASS_LEN_MIN = 3;

    public static $EDAM_NOTE_CONTENT_CLASS_LEN_MAX = 32;

    public static $EDAM_HELLO_APP_CONTENT_CLASS_PREFIX = "evernote.hello.";

    public static $EDAM_FOOD_APP_CONTENT_CLASS_PREFIX = "evernote.food.";

    public static $EDAM_NOTE_CONTENT_CLASS_REGEX = "^[A-Za-z0-9_.-]{3,32}\$";

    public static $EDAM_CONTENT_CLASS_HELLO_ENCOUNTER = "evernote.hello.encounter";

    public static $EDAM_CONTENT_CLASS_HELLO_PROFILE = "evernote.hello.profile";

    public static $EDAM_CONTENT_CLASS_FOOD_MEAL = "evernote.food.meal";

    public static $EDAM_CONTENT_CLASS_SKITCH = "evernote.skitch";

    public static $EDAM_CONTENT_CLASS_PENULTIMATE = "evernote.penultimate";

    public static $EDAM_RELATED_PLAINTEXT_LEN_MIN = 1;

    public static $EDAM_RELATED_PLAINTEXT_LEN_MAX = 131072;

    public static $EDAM_RELATED_MAX_NOTES = 25;

    public static $EDAM_RELATED_MAX_NOTEBOOKS = 1;

    public static $EDAM_RELATED_MAX_TAGS = 25;

    public static $EDAM_BUSINESS_NOTEBOOK_DESCRIPTION_LEN_MIN = 1;

    public static $EDAM_BUSINESS_NOTEBOOK_DESCRIPTION_LEN_MAX = 200;

    public static $EDAM_BUSINESS_NOTEBOOK_DESCRIPTION_REGEX = "^[^\\p{Cc}\\p{Z}]([^\\p{Cc}\\p{Zl}\\p{Zp}]{0,198}[^\\p{Cc}\\p{Z}])?\$";

    public static $EDAM_PREFERENCE_NAME_LEN_MIN = 3;

    public static $EDAM_PREFERENCE_NAME_LEN_MAX = 32;

    public static $EDAM_PREFERENCE_VALUE_LEN_MIN = 1;

    public static $EDAM_PREFERENCE_VALUE_LEN_MAX = 1024;

    public static $EDAM_MAX_PREFERENCES = 100;

    public static $EDAM_MAX_VALUES_PER_PREFERENCE = 250;

    public static $EDAM_PREFERENCE_NAME_REGEX = "^[A-Za-z0-9_.-]{3,32}\$";

    public static $EDAM_PREFERENCE_VALUE_REGEX = "^[^\\p{Cc}]{1,1024}\$";

    public static $EDAM_DEVICE_ID_LEN_MAX = 32;

    public static $EDAM_DEVICE_ID_REGEX = "^[^\\p{Cc}]{1,32}\$";

    public static $EDAM_DEVICE_DESCRIPTION_LEN_MAX = 64;

    public static $EDAM_DEVICE_DESCRIPTION_REGEX = "^[^\\p{Cc}]{1,64}\$";
}


